version: "3.9"
services:
  node:
    build:
      context: ./build
      dockerfile: ./Dockerfile
    volumes:
      - ./node_modules:/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.2
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data
  redis:
    image: redis:6.2.1
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
